STATUS = "status"
ERROR = "error"
USERNAME = "username"
MOBILE = "mobile"
PASSWORD = "password"
TOKEN = "token"
DEVICE_ID = "deviceId"
PERSONAL = "personal"
GROUPS = "groups"
TASKS = "tasks"
FRIENDS = "friends"

GROUP = "group"
GROUP_ID = "groupId"
GROUP_NAME = "groupName"
GROUP_OWNER = "groupOwnerId"
GROUP_TIMESTAMP = "createdTimestamp"

TASK = "task"
TASK_ID = "taskId"
TASK_GROUP_ID = GROUP_ID
TASK_TIMESTAMP = GROUP_TIMESTAMP
TASK_NAME = "taskName"
TASK_DESC = "taskDescription"
TASK_DUE_DATE = "dueDate"
TASK_IS_REPEAT = "isRepeat"
TASK_REPEAT_FREQ = "repeatFrequency"
TASK_REPEAT_FREQ_UNIT = "repeatFrequencyUnit"
TASK_IS_COMPLETE = "isComplete"
TASK_COMPLETE_TIMESTAMP = "completeTimestamp"
TASK_ASSIGNED_BY = "assignedBy"
TASK_ASSIGNED_TO = "assignedTo"

FRIEND = "friend"

RESULT_CODE = "code"
RESULT = "result"
MSG = "msg"
DATA = "data"